version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/bookApp
      - /bookApp/node_modules
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASS: 123456
      DATABASE_NAME: bookManagement
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bookManagement
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
